### ISSUE TITLE
Czech is in main.js but not switch admin interface

### ISSUE THREAD

**Issue by mtrakal** [juanda99/arasaac-admin#58]
Current state:
- open any admin page
- switch language to English / Spanish
- try to switch to Czech
- web still in English (default language)

Expected:
- web interface switch to Czech

When I checked [main.js](https://admin.arasaac.org/main.ad589f81e477f4530740.chunk.js) it contains czech translation, but from some reason it don't know about czech translation and uses default language (en).

https://github.com/juanda99/arasaac-admin/assets/1458891/20e0a9dd-11c0-4b8f-8bcf-20f0038ac13f

**Comment by juanda99** [comment]
Fixed, not all translations were uploaded (synced) to our server, so default (English) was used in that cases. Thanks!
