### ISSUE TITLE
Question: Is ok, that not-validated pictograms are public?

### ISSUE THREAD

**Issue by mtrakal** [juanda99/arasaac-admin#59]
When we start translating pictogram, we fill some data in Czech and it's immediatelly visible for all users.  

I understad, that checkbox is for remove it from `Not validated` list in admin web. But check my example in next sentences...

For example: I start typing, write only half of translatioin and go for tea/lunch/etc... users already see unfinished work in public!

Is that ok?

I think, that it should be published only when we check Validated on screen.

<img width="1842" alt="image" src="https://github.com/juanda99/arasaac-admin/assets/1458891/e3e1f3aa-e13e-460f-9733-5deb5d861614">

Why I check this and why I prefer to publish only Validated ones?

I wrote a script, it downloads all untranslated pictograms (download all, but take only where is no translation yet and fill it with English version but translated to target language with Machine Lerning (google translate / DeepL / Bing translator) it's on user or he can edit it manually) + fill properly `Type of word` (same as in english source) and update `lastModified` date + remove `meaning` because I check, that's not uploaded from web interface. 

I'm able to publish "drafts" which are almost usable but need to be verified by translator before publishing to end users.

It works quite well and can save tons of manual typing to translators, but it has issues like wrong translations for singular vs plural where it uses different words etc...

Edit:
when I try to upload pictogram over API which has older lastModified than pictogram on server, is it ignored? Returned as conflict/etc? I could use older lastModified in script to be sure, that I never override some translation which did another translator.

**Comment by juanda99** [comment]
When we designed the pictogram translation tool, we chose to make the pictograms visible (public status) once their design (image) was ready. Since then they are visible as long as there is a word that describes them in each language. The validated status simply allows the translator to know the status of their translations, but all published pictograms are accessible by users, regardless of whether they are validated or not. Doing a "double validation", general (publish state) and by language (validated), would have been very cumbersome because the work of translations is voluntary and we cannot exercise control or monitoring over languages ​​that we do not know either.
We prefer to get bad results to not having anything at all.

lastModified field is just used to know the translators activity.

**Comment by mtrakal** [comment]
Maybe I was not correct in the description. It's not about whole pictogram, it should be visible, but about translations/keywords only.

For example: https://arasaac.org/pictograms/cs/2243/ is translated and validated. 
I can see czech keywords for it from: https://privateapi.arasaac.org/api/pictograms/keywords/cs/2243
<img width="352" alt="image" src="https://github.com/juanda99/arasaac-admin/assets/1458891/93216b5b-2820-48cd-a755-c5b8ebfd8572">

---
In this case: https://arasaac.org/pictograms/cs/21953/ I don't see any keywords, because it's not translated.
<img width="339" alt="image" src="https://github.com/juanda99/arasaac-admin/assets/1458891/40578bf0-2a1f-4875-9fca-b1c5f4294fa2">


It is without keywords now, but still accessible - I can see the pictogram by category tree:
<img width="1027" alt="image" src="https://github.com/juanda99/arasaac-admin/assets/1458891/4e20df8e-b568-4dd6-a2ae-a7a8e23e6bcc">

---
But in case: 
https://arasaac.org/pictograms/cs/2259/ it's not validated.
So I expect, that https://privateapi.arasaac.org/api/pictograms/keywords/cs/2259 will return empty list for Czech.
Of course I can get english keywords: https://privateapi.arasaac.org/api/pictograms/keywords/en/2259 and see them.

What I expect in this case is empty list for czech until we check Validated on admin: https://admin.arasaac.org/pictograms/2259

```kotlin
    @GET("/pictograms/keywords/[locale]/[pictogramId]")
    fun getPictogramKeywords(locale: String, pictogramId: Int) {
        val pictogram = getPictogramById(pictogramId, locale)
        return if (pictogram.validated) {
            // show country specific keywords only when validated
            listOf(pictogram.keywords)
        } else {
            emptyList()
        }
    }
```


Out of this story:
I think, that public https://arasaac.org/pictograms/cs/2259/ should not request keywords from [**privateapi**.arasaac.org](https://privateapi.arasaac.org/api/pictograms/keywords/cs/2259), but from some public one like  https://api.arasaac.org/v1/pictograms/cs/2259

**Comment by juanda99** [comment]
All keyword translations are public once they are set. No need to pass the validate status. Some times we detect our way of "naming" the pictograms is not correct enough. It's then when we use it to mark the pictograms for review.
