### ISSUE TITLE
Bulk update translations

### ISSUE THREAD

**Issue by mtrakal** [juanda99/arasaac-admin#60]
When we would use the script for upload keyword translations, it would be nice, when I can upload more than one pictogram per request.

Current state:
We can upload only one pictogram.

`https://privateapi.arasaac.org/api/pictograms` with body
```json
{
  "locale": "cs",
  "pictogram": {
    "_id": 2282,
    ...
  }
}
```

Expected state:
we can upload bulk of pictograms (not all, but only new translated) like:
```json
{
  "locale": "cs",
  "pictograms": [
    {
      "_id": 1,
      ...
    },
    {
      "_id": 2,
      ...
    }
  ]
}
```

It could help a lot, because otherwise, I will upload it one by one and establish a ton of connections. It will take much more time, it will create a small "DOS attack" (I have prepared some delay between requests and do not plan to use parallel requests :)).

Working project is here (I've tested it with only one uploaded pictogram, not use whole bulk for now): https://github.com/mtrakal/arasaac-bulk-translator

**Comment by juanda99** [comment]
Private api is not documented because it's thought for beeing used only from our own program, where pictograms are updated one by one.
It can be error prone to upload pictograms this way so I prefer not to open this door. I can provide you the pictogram JSON collection in your language and then give it back to us so we can check that nothing more than keywords is modified?

**Comment by mtrakal** [comment]
Modified is only keywords + lastUpdated.
`"hasLocution": false` is set for all keywords (because if I understand correctly it's only for English translation where is possible download mp3 file?) and remove `meaning` (same as web app do).

Diff between https://privateapi.arasaac.org/api/pictograms/cs and updated json with translations:
<img width="944" alt="image" src="https://github.com/juanda99/arasaac-admin/assets/1458891/00cf39a4-f44b-41f7-bb0f-9a30d83e2682">


Diff with Admin web (when I click on ➕ on the current pictogram without keywords and keep input empty) and file which will be updated:
<img width="994" alt="image" src="https://github.com/juanda99/arasaac-admin/assets/1458891/217b6915-56ef-4809-8101-4492f2a1dbec">
Sure, there is no `locale` key because it's not final PUT body, just pictogram object.


So there is only difference in keywords + lastUpdated. Synsets is just diff because of formatter.

**Comment by juanda99** [comment]
ok, perfect!
